---


- name: Add Elasticsearch GPG key into rpm
  shell: rpm --import http://packages.elastic.co/GPG-KEY-elasticsearch

- name: beats repo
  copy:
    src: beats.repo
    dest: /etc/yum.repos.d/
    owner: root
    group: root
    mode: 644

- name: Install filebeats
  yum:
    name: filebeat
    state: present
    update_cache: yes

- name: copy the certs
  copy:
    src: logstash-forwarder.crt
    dest: /etc/pki/tls/certs/
    owner: root
    group: root
    mode: 644

- name: Remove the default filebeat configuration file
  shell: rm /etc/filebeat/filebeat.yml

- name: Replace custom filebeat configuration file
  template:
    src: filebeat.yml
    dest: /etc/filebeat/
    owner: root
    group: root
    mode: 644

- name: Start filebeats
  service:
    name: filebeat
    state: started
    enabled: true
